# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
      working-directory: client
    - run: npm run build --if-present
      working-directory: client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Copy files to destination folder via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cp ${{ secrets.ORIGINPATH}}/api ${{ secrets.DESTINATIONPATH}}/api
          cp ${{ secrets.ORIGINPATH}}/worker ${{ secrets.DESTINATIONPATH}}/worker
          cp ${{ secrets.ORIGINPATH}}/client/build ${{ secrets.DESTINATIONPATH}}/build
    - name: Restart PM2 services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          pm2 restart JobBoardWorker
          pm2 restart JobBoardAPI
          pm2 restart JobBoardFE
          
          
